# Generated by Django 4.0.1 on 2022-03-08 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=100)),
                ("y", models.DecimalField(decimal_places=2, max_digits=100)),
                ("width", models.DecimalField(decimal_places=2, max_digits=100)),
                ("height", models.DecimalField(decimal_places=2, max_digits=100)),
                ("collapsed", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("color", models.CharField(default="#baaf13", max_length=10)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PostIt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=100)),
                ("y", models.DecimalField(decimal_places=2, max_digits=100)),
                ("width", models.DecimalField(decimal_places=2, max_digits=100)),
                ("height", models.DecimalField(decimal_places=2, max_digits=100)),
                ("collapsed", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("color", models.CharField(default="#baaf13", max_length=10)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=100)),
                ("y", models.DecimalField(decimal_places=2, max_digits=100)),
                ("width", models.DecimalField(decimal_places=2, max_digits=100)),
                ("height", models.DecimalField(decimal_places=2, max_digits=100)),
                ("collapsed", models.BooleanField(default=False)),
                ("url", models.URLField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("is_checked", models.BooleanField()),
                (
                    "checklist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="component.checklist",
                    ),
                ),
            ],
        ),
    ]
