# Generated by Django 4.0.1 on 2022-03-23 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='collapsed',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
