# Generated by Django 4.0.1 on 2022-04-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_remove_image_collapsed_alter_checklistitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
