# Generated by Django 4.0.1 on 2022-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_background"),
    ]

    operations = [
        migrations.RenameField(
            model_name="background",
            old_name="workspace_id",
            new_name="workspace",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="background",
            name="image_url",
            field=models.TextField(),
        ),
    ]
