# Generated by Django 4.0.1 on 2022-02-11 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0003_rename_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="workspace.workspace"
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
